spring:
  jackson:
    mapper:
      sort-properties-alphabetically: true
  data.mongodb:
    authentication-database: wallet
    uri: mongodb://uppcladmin:uppcladmin%402020@10.128.51.70:27017/wallet
  cloud:
    stream:
      kafka:
        default:
          producer:
            sync: true
        binder:
          brokers: 20.198.69.198:9092 # localhost:9092
          requiredAcks: all
          autoCreateTopics: true
          autoAddPartitions: true
          producerProperties:
            acks: all
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

hlf:
  mode: LOCAL # LOCAL -> mongo / BOTH -> mongo + blockchain / REMOTE -> blockchain
  url: http://20.204.25.85:9010/api/v1
  isPrimary: false

integration:
  adminNode: https://ewallet-test.uppclonline.com:8280/verify-mail/1.0.0
  adminUser: amadmin
  adminPassword: Welcome@123
  notifyKey: LTtSTXK7aZAXmxaySaJNuscqAIEa
  notifySecret: pUIO803kVFop7FbUBJlbt7gXXh8a
  tokenServer: https://ewallet-test.uppclonline.com:8280/token
  notifyServer: https://ewallet-test.uppclonline.com:8280/notifyuser/1.0.0
  authServer: https://ewallet-test.uppclonline.com:7777
  billPostKey: lgJ8UxNNBHBDtUBNikRgttTkf6sa
  billPostSecret: aBJqn8LJMstNdm0D5w280sekfuIa
  billPostServer: https://ewallet-test.uppclonline.com:8280/billpost/1.0.0
  rapdrpMeterAgentUrl: https://onlinebilling.uppclonline.com/UPPCL/ProxyServices/WalletAPI/OPS
  rapdrpMeterAgentUsername: client_rest
  rapdrpMeterAgentPassword: welcome1
  nonRapdrpMeterAgentConfig:
    meterAgentUrl: http://223.30.74.211:9001/metering/GenxUserDatPost.htm
    meterAgentValidationUrl: http://223.30.74.211:9001/metering/GenxUserValidation.htm
    puvvnlMeterAgentUrl:
    puvvnlMeterAgentValidationUrl:
    mvvnlMeterAgentUrl:
    mvvnlMeterAgentValidationUrl:
    pvvnlMeterAgentUrl:
    pvvnlMeterAgentValidationUrl:
    dvvnlMeterAgentUrl:
    dvvnlMeterAgentValidationUrl:
  mapping:
    tokenUrl: https://ewallet-test.uppclonline.com:8280/token
    username: uppclgenx
    password: APimTDu!2019@
    consumerKey: 3AVfoiZ058fqEndO_8yMN3zkwrEa
    consumerSecret: MfxClLKLhrGWJuMU9hMDC0JaE6ca
    url: https://ewallet-test.uppclonline.com:8280/GetUrbanRural/1.0.0

# second(0-59) minute(0 - 59) hour(0 - 23) day-of-the-month(1 - 31) month(1 - 12/JAN-DEC) day-of-the-week(0 - 7/0 or 7 is Sunday, or MON-SUN)
scheduler:
  meterAgentSync: '0 0 1 * * ?'
  lowWalletBalance: '0 0 10 * * ?'
  blockchainSyncPartial: '* */30 * * * ?' # Every 30 min
  blockchainSyncFull: '0 30 0 * * ?' # at 12:30 AM everyday