spring:
  jackson:
    mapper:
      sort-properties-alphabetically: true
  data.mongodb:
    authentication-database: wallet
    uri: mongodb://uppcladmin:uppcladmin%402020@10.129.14.36:27017,10.129.14.165:27017/wallet?replicaSet=rs0
  cloud:
    stream:
      kafka:
        default:
          producer:
            sync: true
          consumer:
            autoRebalanceEnabled: true
            ackEachRecord: true
            autoCommitOffset: true
            ackMode: RECORD
            autoCommitOnError: true
            startOffset: latest
        binder:
          consumerProperties:
            enable:
              auto:
                commit: true
            default:
              api:
                timeout:
                  ms: 300000
            session:
              timeout:
                ms: 300000
            request:
              timeout:
                ms: 300000
            max:
              poll:
                records: 300
                interval:
                  ms: 300000
          brokers: 10.129.7.12:9092 #,10.129.8.68:9092 # localhost:9092
          requiredAcks: all
          autoCreateTopics: true
          autoAddPartitions: true
          producerProperties:
            acks: all
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

hlf:
  mode: LOCAL # LOCAL -> mongo / BOTH -> mongo + blockchain / REMOTE -> blockchain
  url: http://10.129.20.68:9010/api/v1
  isPrimary: false

integration:
  adminNode: https://ewallet.uppclonline.com:8280/verify-mail/1.0.0
  adminUser: amadmin
  adminPassword: Welcome@123
  notifyKey: CaNEC4YxfSgL9T069wTU1ThDbZ8a
  notifySecret: iYdUfO1eDJIjE7u6LjPUoIHpqyca
  tokenServer: https://ewallet.uppclonline.com:8280/token
  notifyServer: https://ewallet.uppclonline.com:8280/notifyuser/1.0.0
  authServer: https://ewallet.uppclonline.com:7777
  billPostKey: kkeTEHKdbY2rmUpLX8gIJ9dOkqIa
  billPostSecret: SRBOe_tZRMjV4ddFdOucF1Bggdca
  billPostServer: https://ewallet.uppclonline.com:8280/billpost/1.0.0
  rapdrpMeterAgentUrl: https://www.uppclonline.com/UPPCL/ProxyServices/WalletAPI/OPS
  rapdrpMeterAgentUsername: GenXWLUP
  rapdrpMeterAgentPassword: BillingPay@9182
  nonRapdrpMeterAgentConfig:
    meterAgentUrl: http://223.30.74.211:9001/metering/GenxUserDatPost.htm
    meterAgentValidationUrl: http://223.30.74.211:9001/metering/GenxUserValidation.htm
    puvvnlMeterAgentUrl: https://puvvnlmob.mpower.in/metering/GenxUserDatPost.htm
    puvvnlMeterAgentValidationUrl: https://puvvnlmob.mpower.in/metering/GenxUserValidation.htm
    mvvnlMeterAgentUrl: https://mvvnlmob.mpower.in/metering/GenxUserDatPost.htm
    mvvnlMeterAgentValidationUrl: https://mvvnlmob.mpower.in/metering/GenxUserValidation.htm
    pvvnlMeterAgentUrl: https://pvvnlmob.mpower.in/metering/GenxUserDatPost.htm
    pvvnlMeterAgentValidationUrl: https://pvvnlmob.mpower.in/metering/GenxUserValidation.htm
    dvvnlMeterAgentUrl: https://dvvnlmob.mpower.in/metering/GenxUserDatPost.htm
    dvvnlMeterAgentValidationUrl: https://dvvnlmob.mpower.in/metering/GenxUserValidation.htm
  mapping:
    tokenUrl: https://ewallet.uppclonline.com:8280/token
    username: uppclgenx
    password: APimUPrdU!2019@
    consumerKey: L5n5RwGmefxUBTDsYFkjddJBmE4a
    consumerSecret: REuTqallhTzpvdf3zDWoGLahi54a
    url: https://ewallet.uppclonline.com:8280/GetUrbanRural/1.0.0

# second(0-59) minute(0 - 59) hour(0 - 23) day-of-the-month(1 - 31) month(1 - 12/JAN-DEC) day-of-the-week(0 - 7/0 or 7 is Sunday, or MON-SUN)
scheduler:
  meterAgentSync: '0 0 1 * * ?'
  lowWalletBalance: '0 0 10 * * ?'
  blockchainSyncPartial: '* */30 * * * ?' # Every 30 min
  blockchainSyncFull: '0 30 0 * * ?' # at 12:30 AM everyday